---
- name: Install the packages for image optimazation
  apt: name={{item}}
  with_items: "{{packages.image}}"
  tags:
    - packages

- name: Install the packages of the user customaztion
  apt: name={{item}}
  with_items: "{{packages.additional}}"
  when: packages.additional is defined
  tags:
    - packages

- name: Install and configure oh-my-zsh shell for the box
  block:
    - name: Install zsh shell
      apt:
        name: zsh
        state: latest
        update_cache: yes

    - name: Clone oh-my-zsh repository from github
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh
        dest: "{{ item }}/.oh-my-zsh"
      with_items:
        - "/root"
        - "/home/{{vagrant.user}}"

    - name: Set permission for
      file:
        path: "{{ item.home }}/.oh-my-zsh"
        state: directory
        recurse: yes
        owner: "{{ item.username }}"
        group: "{{ item.group }}"
      with_items:
        - { home: "/root", username: "root", group: "root"}
        - { home: "/home/{{vagrant.user}}", username: "{{vagrant.user}}", group: "{{vagrant.group}}"}

    - name: Add syntax highlighting plugin for oh-my-zsh
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "{{ item }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
      with_items:
        - "/root"
        - "/home/{{vagrant.user}}"

    - name: Creating .zshrc file for users
      get_url:
        url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/templates/zshrc.zsh-template
        dest: "{{ item }}/.zshrc"
        mode: 0755
      with_items:
        - "/root"
        - "/home/{{vagrant.user}}"

    - name: Ensure zsh shell is set for all users
      user:
        name: "{{ item }}"
        shell: /bin/zsh
      with_items:
        - "root"
        - "{{vagrant.user}}"
  tags:
    - zsh
