---
- name: Restart nginx
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes
  listen: "Restart Web Server"

- name: Restart php-fpm
  become: yes
  command: /etc/init.d/php-fpm restart
  listen: "Restart Web Server"
