---
- name: Copy nginx configuration file into box
  template:
    src: nginx.conf
    dest: "/etc/nginx/"
    mode: 0644
  notify: Restart Web Server
  tags:
    - webserver

- name: Copy nginx file
  template:
    src: "{{nginx_server.default_config}}"
    dest: /etc/nginx/conf.d/{{ nginx_project_name }}.conf
    force: yes
  notify: Restart Web Server
  tags:
    - webserver

- name: Delete default nginx file
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Copy php-fpm config file
  template:
    src: php-fpm.conf
    dest: /opt/php/etc
    owner: root
    group: root
    mode: 0644
  notify: Restart Web Server
  tags:
    - webserver

- name: Set php fpm site config file
  template:
    src: www.conf
    dest: /opt/php/etc/php-fpm.d
    owner: root
    group: root
    mode: 0644
  notify: Restart Web Server
  tags:
    - webserver
